[project]
name = 'time-banking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.escrow-manager]
path = 'contracts/escrow-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.exchange-manager]
path = 'contracts/exchange-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 4
epoch = 'latest'

[contracts.skill-registry]
path = 'contracts/skill-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.time-bank-core]
path = 'contracts/time-bank-core.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
