[project]
name = 'time-banking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.time-bank-core]
path = 'contracts/time-bank-core.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
